version: '3.8'

services:
  db:
    image: "postgres:14.1"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
      - "5433:5433"
    restart: always
    networks:
      - booking
    deploy:
      resources:
        limits:
          memory: '100M'
        reservations:
          memory: '0'

  app:
    build: ./
    command: ./app
    restart: always
    ports:
      - ${HTTP_PORT}:8081
    depends_on:
      - db
    environment:
      - DB_SCHEME=${DB_SCHEME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    deploy:
      resources:
        limits:
          memory: '100M'
        reservations:
          memory: '0'

    networks:
      - booking


networks:
  booking:

volumes:
  db: